version: '3'

dotenv:
  - .env

tasks:
  # prepare:
  #   cmd: go mod tidy

  # lint:
  #   cmds:
  #     - golangci-lint run ./cmd

  # test:
  #   cmds:
  #     - go test -cover ./cmd

  # compile:
  #   cmd: GOOS=linux go build -o ./bin/goapp ./goapp

  build:
    cmds:
      - docker build --pull --rm -f ./api.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest .
      - docker build --pull --rm -f ./info.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest .
      - docker build --pull --rm -f ./login.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest .
      - docker build --pull --rm -f ./root.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest .

  push:
    cmds:
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest

  deploy:
    cmds: 
      - kubectl apply -f ./deployments/config-env-api.yaml
      - kubectl apply -f ./deployments/config-env-info.yaml
      - kubectl apply -f ./deployments/config-env-login.yaml
      - kubectl apply -f ./deployments/config-env-root.yaml
      - kubectl apply -f ./deployments/k8s/deployments.yaml
      - kubectl apply -f ./deployments/services.yaml 
      - kubectl apply -f ./deployments/ingress.yaml
  
  uninstall:
    cmds:
      - kubectl delete -f ./deployments/config-env-api.yaml
      - kubectl delete -f ./deployments/config-env-info.yaml
      - kubectl delete -f ./deployments/config-env-login.yaml
      - kubectl delete -f ./deployments/config-env-root.yaml
      - kubectl delete -f ./deployments/k8s/deployments.yaml
      - kubectl delete -f ./deployments/services.yaml 
      - kubectl delete -f ./deployments/ingress.yaml

  release:
    cmds:
      # - task: prepare
      # - task: lint
      # - task: test
      # - task: compile
      - task: build
      - task: push
      - task: deploy